version: "3.1"

services:
  database:
    image: mysql:8
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /c/Users/jonat/github/team-portal/docker/mysql/initial-content:/docker-entrypoint-initdb.d
      - /c/Users/jonat/github/team-portal/docker/mysql/content:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 8025:8025
      - 1025:1025

  joomla:
    image: joomla
    environment:
      JOOMLA_DB_HOST: database:mysql
      JOOMLA_DB_USER: root
      JOOMLA_DB_PASSWORD: root
      JOOMLA_DB_NAME: deb105013n2_SKC
    ports:
      - 8080:80
